// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadPicker.Data;

namespace SquadPicker.Data.Migrations
{
    [DbContext(typeof(SquadPickerContext))]
    [Migration("20211122142522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SquadPicker.Models.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Defenders")
                        .HasColumnType("int");

                    b.Property<int>("Forwards")
                        .HasColumnType("int");

                    b.Property<int>("Goalkeepers")
                        .HasColumnType("int");

                    b.Property<int>("Midfielders")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fd98659-4a59-4104-b3bf-66c065c1e81f"),
                            Defenders = 4,
                            Forwards = 2,
                            Goalkeepers = 1,
                            Midfielders = 4,
                            Name = "4-4-2"
                        },
                        new
                        {
                            Id = new Guid("89889a27-93f5-4de2-a3b3-fdf6a974ed61"),
                            Defenders = 5,
                            Forwards = 2,
                            Goalkeepers = 1,
                            Midfielders = 3,
                            Name = "5-3-2"
                        },
                        new
                        {
                            Id = new Guid("5892ddf2-079d-4a6d-8f4b-e0a72039fb53"),
                            Defenders = 4,
                            Forwards = 3,
                            Goalkeepers = 1,
                            Midfielders = 3,
                            Name = "4-3-3"
                        });
                });

            modelBuilder.Entity("SquadPicker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jordan Pickford",
                            Position = 1,
                            Selected = false
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sam Johnstone",
                            Position = 1,
                            Selected = false
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aaron Ramsdale",
                            Position = 1,
                            Selected = false
                        },
                        new
                        {
                            Id = 4,
                            Name = "Trent Alexander-Arnold",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ben Chilwell",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 6,
                            Name = "Conor Coady",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 7,
                            Name = "Reece James",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 8,
                            Name = "Harry Maguire",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tyrone Mings",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 10,
                            Name = "Luke Shaw",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 11,
                            Name = "John Stones",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kyle Walker",
                            Position = 2,
                            Selected = false
                        },
                        new
                        {
                            Id = 13,
                            Name = "Jude Bellingham",
                            Position = 3,
                            Selected = false
                        },
                        new
                        {
                            Id = 14,
                            Name = "Jordan Henderson",
                            Position = 3,
                            Selected = false
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mason Mount",
                            Position = 3,
                            Selected = false
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kalvin Phillips",
                            Position = 3,
                            Selected = false
                        },
                        new
                        {
                            Id = 17,
                            Name = "Declan Rice",
                            Position = 3,
                            Selected = false
                        },
                        new
                        {
                            Id = 18,
                            Name = "James Ward-Prowse",
                            Position = 3,
                            Selected = false
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tammy Abraham",
                            Position = 4,
                            Selected = false
                        },
                        new
                        {
                            Id = 20,
                            Name = "Phil Foden",
                            Position = 4,
                            Selected = false
                        },
                        new
                        {
                            Id = 21,
                            Name = "Jack Grealish",
                            Position = 4,
                            Selected = false
                        },
                        new
                        {
                            Id = 22,
                            Name = "Harry Kane",
                            Position = 4,
                            Selected = false
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bukayo Saka",
                            Position = 4,
                            Selected = false
                        },
                        new
                        {
                            Id = 24,
                            Name = "Marcus Rashford",
                            Position = 4,
                            Selected = false
                        },
                        new
                        {
                            Id = 25,
                            Name = "Raheem Sterling",
                            Position = 4,
                            Selected = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
