// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadPicker.Data;

namespace SquadPicker.Data.Migrations
{
    [DbContext(typeof(SquadPickerContext))]
    [Migration("20211122215439_AddUserIdToTeam")]
    partial class AddUserIdToTeam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SquadPicker.Models.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Defenders")
                        .HasColumnType("int");

                    b.Property<int>("Forwards")
                        .HasColumnType("int");

                    b.Property<int>("Goalkeepers")
                        .HasColumnType("int");

                    b.Property<int>("Midfielders")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eb1b188-e7fc-461b-b52b-85eba8f3896b"),
                            Defenders = 4,
                            Forwards = 2,
                            Goalkeepers = 1,
                            Midfielders = 4,
                            Name = "4-4-2"
                        },
                        new
                        {
                            Id = new Guid("90fcf596-1885-457e-a414-9ecbef4ed6af"),
                            Defenders = 5,
                            Forwards = 2,
                            Goalkeepers = 1,
                            Midfielders = 3,
                            Name = "5-3-2"
                        },
                        new
                        {
                            Id = new Guid("b909326a-fe7b-450a-afaa-5e64af2ffbe3"),
                            Defenders = 4,
                            Forwards = 3,
                            Goalkeepers = 1,
                            Midfielders = 3,
                            Name = "4-3-3"
                        });
                });

            modelBuilder.Entity("SquadPicker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Validity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jordan Pickford",
                            Position = 1,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sam Johnstone",
                            Position = 1,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aaron Ramsdale",
                            Position = 1,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Trent Alexander-Arnold",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ben Chilwell",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Conor Coady",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Reece James",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Harry Maguire",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tyrone Mings",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Luke Shaw",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 11,
                            Name = "John Stones",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kyle Walker",
                            Position = 2,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Jude Bellingham",
                            Position = 3,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Jordan Henderson",
                            Position = 3,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mason Mount",
                            Position = 3,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kalvin Phillips",
                            Position = 3,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Declan Rice",
                            Position = 3,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 18,
                            Name = "James Ward-Prowse",
                            Position = 3,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tammy Abraham",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Phil Foden",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Jack Grealish",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Harry Kane",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bukayo Saka",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Marcus Rashford",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Raheem Sterling",
                            Position = 4,
                            Selected = false,
                            Validity = "player-valid"
                        });
                });

            modelBuilder.Entity("SquadPicker.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateUTC")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FormationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SquadPicker.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SquadPicker.Models.Player", b =>
                {
                    b.HasOne("SquadPicker.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("SquadPicker.Models.Team", b =>
                {
                    b.HasOne("SquadPicker.Models.Formation", "Formation")
                        .WithMany()
                        .HasForeignKey("FormationId");

                    b.HasOne("SquadPicker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
