// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadPicker.Data;

namespace SquadPicker.Data.Migrations
{
    [DbContext(typeof(SquadPickerContext))]
    [Migration("20211124180630_AddForeignKeyFromPlayerToUser")]
    partial class AddForeignKeyFromPlayerToUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SquadPicker.Models.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Defenders")
                        .HasColumnType("int");

                    b.Property<int>("Forwards")
                        .HasColumnType("int");

                    b.Property<int>("Goalkeepers")
                        .HasColumnType("int");

                    b.Property<int>("Midfielders")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c104e680-fcc6-471e-9409-591f8c5c9f38"),
                            Defenders = 4,
                            Forwards = 2,
                            Goalkeepers = 1,
                            Midfielders = 4,
                            Name = "4-4-2"
                        },
                        new
                        {
                            Id = new Guid("5f8770e5-4394-452e-9ced-8536bc947b36"),
                            Defenders = 5,
                            Forwards = 2,
                            Goalkeepers = 1,
                            Midfielders = 3,
                            Name = "5-3-2"
                        },
                        new
                        {
                            Id = new Guid("77eb4f29-7019-42c7-8dce-d760b686c0fa"),
                            Defenders = 4,
                            Forwards = 3,
                            Goalkeepers = 1,
                            Midfielders = 3,
                            Name = "4-3-3"
                        });
                });

            modelBuilder.Entity("SquadPicker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Validity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "Jordan Pickford",
                            Position = 1,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "Sam Johnstone",
                            Position = 1,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "Aaron Ramsdale",
                            Position = 1,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "Trent Alexander-Arnold",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Name = "Ben Chilwell",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 6,
                            Deleted = false,
                            Name = "Conor Coady",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 7,
                            Deleted = false,
                            Name = "Reece James",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 8,
                            Deleted = false,
                            Name = "Harry Maguire",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 9,
                            Deleted = false,
                            Name = "Tyrone Mings",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 10,
                            Deleted = false,
                            Name = "Luke Shaw",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 11,
                            Deleted = false,
                            Name = "John Stones",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 12,
                            Deleted = false,
                            Name = "Kyle Walker",
                            Position = 2,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 13,
                            Deleted = false,
                            Name = "Jude Bellingham",
                            Position = 3,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 14,
                            Deleted = false,
                            Name = "Jordan Henderson",
                            Position = 3,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 15,
                            Deleted = false,
                            Name = "Mason Mount",
                            Position = 3,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 16,
                            Deleted = false,
                            Name = "Kalvin Phillips",
                            Position = 3,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 17,
                            Deleted = false,
                            Name = "Declan Rice",
                            Position = 3,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 18,
                            Deleted = false,
                            Name = "James Ward-Prowse",
                            Position = 3,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 19,
                            Deleted = false,
                            Name = "Tammy Abraham",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 20,
                            Deleted = false,
                            Name = "Phil Foden",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 21,
                            Deleted = false,
                            Name = "Jack Grealish",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 22,
                            Deleted = false,
                            Name = "Harry Kane",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 23,
                            Deleted = false,
                            Name = "Bukayo Saka",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 24,
                            Deleted = false,
                            Name = "Marcus Rashford",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        },
                        new
                        {
                            Id = 25,
                            Deleted = false,
                            Name = "Raheem Sterling",
                            Position = 4,
                            Selected = false,
                            UserId = new Guid("4be180ee-1af1-4a19-a5f4-8105ad3ef124"),
                            Validity = "player-valid"
                        });
                });

            modelBuilder.Entity("SquadPicker.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FormationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SquadPicker.Models.TeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("SquadPicker.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SquadPicker.Models.Player", b =>
                {
                    b.HasOne("SquadPicker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SquadPicker.Models.Team", b =>
                {
                    b.HasOne("SquadPicker.Models.Formation", "Formation")
                        .WithMany("Teams")
                        .HasForeignKey("FormationId");

                    b.HasOne("SquadPicker.Models.User", "User")
                        .WithMany("Teams")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SquadPicker.Models.TeamPlayer", b =>
                {
                    b.HasOne("SquadPicker.Models.Player", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_TeamPlayers_Players")
                        .IsRequired();

                    b.HasOne("SquadPicker.Models.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_TeamPlayers_Teams")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
